version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: .
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  mongo_data:
